name: Premkumar Masilamani
description: On a journey called Life

# The below value is used only in feed.xml
feed-url: http://blog.smileprem.com

# The below url value is not mandatory
#url: http://blog.smileprem.com
#url: http://localhost:4000

paginate: 10

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

pygments: true
safe: false
lsi: false

permalink: /:title/

