title: smileprem
tagline: on a journey called life
url: http://blog.smileprem.com
#logo: add-some-logo-here
copyright: copyleft @ 2009. free to all.

author: Premkumar Masilamani
email: xxx@xxx.xxx
mobile: xxx-xxx-xxxx

social:
  name: Premkumar Masilamani
  links:
    - http://www.linkedin.com/in/premkumarmasilamani
    - https://github.com/smileprem

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 150

permalink: /:title/

img-path: http://blog.smileprem.com/public/images
download-path: http://blog.smileprem.com/public/downloads

newsletter: http://eepurl.com/VMDl5
tamil-blog: https://tamil.smileprem.com/
