name: Premkumar Masilamani
description: On a journey called Life
url: http://prem82.github.io
#url: http://localhost:4000

paginate: 10

markdown: redcarpet
pygments: true
safe: false
lsi: false

permalink: /:title/

