title:            smileprem
tagline:          on a journey called life
url:              http://blog.smileprem.com
copyright:        copyleft @ 2009. free to all.

author:           homo sapien
email:            xxx@xxx.xxx
mobile:           xxx-xxx-xxxx 
tamil:            http://tamil.smileprem.com
rawvegan:         http://www.raw-vegan-recipes.com
facebook:         http://www.facebook.com/i-do-not-use-fb
twitter:          http://twitter.com/i-do-not-use-twitter
linkedin:         http://www.linkedin.com/in/premkumarmasilamani

gems:             [jekyll-paginate]
paginate:         150

permalink:        /:title/

img-path:         http://blog.smileprem.com/public/img
download-path:    http://blog.smileprem.com/public/downloads

