name: Premkumar Masilamani
description: On a journey called Life
url: http://blog.smileprem.com

paginate: 10

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

pygments: true
safe: false
lsi: false

permalink: /:title/
relative_permalinks: false


