title: smileprem
tagline: on a journey called life
url: https://blog.smileprem.com
#logo: add-some-logo-here
copyright: copyleft @ 2009. free to all.

author: Premkumar Masilamani
email: xxx@xxx.xxx
mobile: xxx-xxx-xxxx

social:
  name: Premkumar Masilamani
  links:
    - http://www.linkedin.com/in/premkumarmasilamani
    - https://github.com/smileprem

include:
  - "_pages"

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

paginate: 150

permalink: /:title/

img-path: https://blog.smileprem.com/public/images
download-path: https://blog.smileprem.com/public/downloads

newsletter: http://eepurl.com/dE1QD1
contact-form: https://www.emailmeform.com/builder/form/bi73zffJbc078cHP6p6fhfr
tamil-blog: https://tamil.smileprem.com/

donation: https://www.blockchain.com/btc/address/14hjWY7QzpD5mjPhmYs8FHrm3aJiEKX82s
