name: Premkumar Masilamani
description: On a journey called Life
url: http://prem82.github.io

paginate: 10

markdown: redcarpet
pygments: true
safe: false
lsi: false

permalink: pretty

redirects: yes

